---
deployment:
  tasks:
    - export DEPLOYPATH=/home/semestat/manrisk-app
    - cd $DEPLOYPATH && /opt/alt/php83/usr/bin/php artisan migrate --force --no-interaction
    - cd $DEPLOYPATH && /opt/alt/php83/usr/bin/php artisan optimize
    - cd $DEPLOYPATH && /opt/alt/php83/usr/bin/php artisan storage:unlink >/dev/null 2>&1 || true
